[package]
name = "mindstormer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.17"
quick-xml = "0.28.2"
zip = "0.6.4"
